Repository SOPT-all/36-COLLABORATION-iOS-HYUNDAICARDDIVE, pull requests merged in 2025-05, with the labels that each got.

#1 [docs] 깃이그노어 수정
  .gitignore
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Base.lproj/.gitkeep
Labels: 📚docs, 🐯hyunsoo

#5 [setting/#3] 컬러에셋 등록
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Black&White/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Black&White/black_10.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Black&White/black_30.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Black&White/black_50.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Black&White/white_40.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/gray1.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/gray2.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/gray3.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/gray4.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Gray scale/gray5.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Point/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Point/point_green.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Point/point_red.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/Point/point_yellow.colorset/Contents.json
Labels: 🎨setting, 🦊youngseo

#8 [add] 컬러 에셋 폴더링
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/AccentColor.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/AppIcon.appiconset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Black&White/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Black&White/black_10.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Black&White/black_30.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Black&White/black_50.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Black&White/white_40.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray1.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray2.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray3.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray4.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray5.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Point/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Point/point_green.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Point/point_red.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Point/point_yellow.colorset/Contents.json
Labels: 🤿add, 🐯hyunsoo

#10 [setting/#9] Extension, Base, Utils 추가
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Base/BaseCollectionReusableView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Base/BaseCollectionViewCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Base/BaseView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Base/BaseViewController.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Extensions/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Extensions/UIStackView+.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Extensions/UIView+.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Fonts/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Utils/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Utils/ReuseIdentifiable.swift
Labels: 🐯hyunsoo, 🎨setting

#18 [chore] 탭바 아이콘 위치 수정
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/AppIcon1.appiconset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_act.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_act.imageset/ic_navi_culture_act.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_act.imageset/ic_navi_culture_act.svg
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_deact.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_deact.imageset/ic_navi_culture_deact.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_culture_deact.imageset/ic_navi_culture_deact.svg
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_act.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_act.imageset/ic_navi_home_act.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_act.imageset/ic_navi_home_act.svg
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_deact.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_deact.imageset/ic_navi_home_deact.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_home_deact.imageset/ic_navi_home_deact.svg
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_profile_deact.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_profile_deact.imageset/ic_navi_profile_deact.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_navi_profile_deact.imageset/ic_navi_profile_deact.svg
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Core/MainTabBarController.swift
Labels: 💎feat, 🦊youngseo

#20 [setting/#14] 네트워크 세팅
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/AppConfig.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Info.plist
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/APIManager.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/APIType.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/BaseService.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/Environment.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/NetworkError.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/NetworkLogger.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/BaseDTO/BaseResponseBody.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/SpaceInfo/SpaceInfoResponseDTO.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Service/SpaceInfo/SpaceInfoService.swift
Labels: 🐯hyunsoo, 🎨setting

#33 [fix/#32] Space&Culture 상세화면 뷰 컨트롤러 추가
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureDetailViewController.swift
Labels: 🔗fix, 🦙seungjun

#35 [feat/#18] 슬라이드 홈 뷰 구현
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Extensions/UILabel+.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray4.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Colors.xcassets/Gray scale/gray5.colorset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/Cell/CategoryChipCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/Cell/HomeSlideCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/Model/HomeSlideModel.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/View/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/View/CategoryView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/View/HomeSlideView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/View/HomeView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/ViewController/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/ViewController/CategoryViewController.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 💎feat, 🦊youngseo

#38 [feat/#25] SpaceInfoView UI 구현
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Base.lproj/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Components/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Components/VisitorListCollectionViewCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/btn_introduce_like.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/btn_introduce_like.imageset/btn_introduce_like.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/btn_introduce_like_act.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/btn_introduce_like_act.imageset/btn_introduce_like_act.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_next.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/icn/ic_next.imageset/ic_next.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/SpaceInfo/SpaceInfoResponseDTO.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Service/SpaceInfo/SpaceInfoService.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Core/MainTabBarController.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/CardInfoView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/GraphImageView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/MapView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/NoticeView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/QuestionView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/SearchBookView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/ShareBannerView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/SpaceInfoView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/VisitorView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/ViewController/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/ViewController/SpaceInfoViewController.swift
Labels: 💎feat, 🐯hyunsoo

#41 [feat/#39] SpaceInfoView API 작업
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Components/VisitorListCollectionViewCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Info.plist
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/APIManager.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Base/APIType.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/BaseDTO/BaseResponseBody.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/SpaceInfo/SpaceInfoResponseDTO.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/SpaceInfoView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/View/VisitorView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceInfo/ViewController/SpaceInfoViewController.swift
Labels: 💎feat, 🐯hyunsoo

#42 [feat/#34] Space&Culture 상세보기 화면 구현
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS.xcodeproj/project.pbxproj
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/img/ios_img_barcord.imageset/Contents.json
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Resource/Assets.xcassets/img/ios_img_barcord.imageset/ios_img_barcord.png
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Cell/ArticleCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/CollectionView/ArticleView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Model/SpaceCultureDetailModel.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/DesignLibraryHeaderView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/DesignLibraryMenuView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/DesingLibraryCheckInView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/SpaceCultureDetailView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/.gitkeep
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureDetailViewController.swift
Labels: 💎feat, 🦙seungjun

#44 [feat/#43] Space&Culture 진입 화면 네트워크 연결
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Global/Utils/DataBindableCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/SpaceCulture/SpaceCultureResponseDto.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Service/SpaceCulture/SpaceCultureService.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Cell/CultureCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Cell/SpaceCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Cell/WhatsOnCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureViewController.swift
Labels: 💎feat, 🦙seungjun

#47 [feat/#45] Space&Culture 상세 화면 네트워크 연결 구현
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/DTO/SpaceCulture/SpaceCultureDetailResponseDto.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Network/Service/SpaceCulture/SpaceCultureDetailService.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Cell/ArticleCell.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Model/SpaceCultureDetailModel.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/Model/WhatsOnModel.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/DesignLibraryHeaderView.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureDetailViewController.swift
Labels: 💎feat, 🦙seungjun

#50 [refactor/#48] createGroup 메서드 활용
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/SpaceCultureCompositionalLayoutFactory.swift
Labels: 📦refactor, 🦙seungjun

#54 [refactor/#53] 내비게이션바 커스텀 오류 해결
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Application/SceneDelegate.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/Core/MainTabBarController.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureDetailViewController.swift
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/ViewController/SpaceCultureViewController.swift
Labels: 📦refactor, 🦙seungjun

#56 [refactor/#55] Space&Culture 상세 화면 스크롤 오류 해결
  HYUNDAICARDDIVE_iOS/HYUNDAICARDDIVE_iOS/Presentation/SpaceCulture/View/SpaceCultureDetailView.swift
Labels: 📦refactor, 🦙seungjun
